### ISSUE TITLE
option to remove `:_r` key indicating

### ISSUE THREAD

**Issue by avelino** [kbosompem/bb-excel#12]
in some cases I don't need to know the indicating (line) of excel, we could have an option to remove the key `:_r`

**example:**
```clj
(print-table
   (get-sheet "test/data/simple.xlsx" "Shows" 
              {:line false
               :hdr true
               :fxn bb-excel.cli/skeyword}))
```

`:line` by default is `true` _(keeps the `:_r` column)_, by setting it to `false` it `dissoc` in  `:_r`

```output
| :rank |        :tv_show |
+-------+-----------------|
|   1.0 |   Sesame Street |
|   2.0 | La Femme Nikita |
|   3.0 |       House M.D |
|   4.0 |    Breaking Bad |
```

**Comment by velios** [comment]
@avelino It's pretty easy to handle with code like this. Are you sure this need separate option? It's seems like dbg print option. Or you use it another way? 
`(print-table
 (map #(dissoc % :_r)
      (get-sheet (io/file "/Users/flocktory/Code/bb-excel/test/data/simple.xlsx") 1)))`

**Comment by avelino** [comment]
that's how I solved it
I thought it would be interesting for the project to have an option to remove the line number

by closing the issue

**Comment by velios** [comment]
@avelino Maybe it is interesting. Adding this option is a very simple thing, I would just like to make sure before that that this is a popular function and look more at possible ways of using it.
