### ISSUE TITLE
can't find sheet name in `.xls` file

### ISSUE THREAD

**Issue by avelino** [kbosompem/bb-excel#13]
```out
clojure.lang.ExceptionInfo: clojure.lang.ExceptionInfo in Interceptor  - Could not find sheet with name or index
equal 'test'! Sheet does not exist. {:execution-id 2, :stage :enter, :interceptor nil, :exception-type :clojure.l
ang.ExceptionInfo, :exception #error {
 :cause "Could not find sheet with name or index equal 'test'! Sheet does not exist."
 :data {}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "Could not find sheet with name or index equal 'test'! Sheet does not exist."
   :data {}
   :at [bb_excel.util$throw_ex invokeStatic "util.clj" 27]}]
```

**[source](https://github.com/moclojer/moclojer/blob/be0bc86cc6fa4abaa4703fa9ca4e56c005a92438/src/moclojer/external_body/excel.clj#L4-L9):**

```clj
(defn ->map
  "converts excel (xlsx and xls) tab/sheet name to map"
  [path sheet-name]
  (map #(dissoc % :_r)
       (excel/get-sheet
        path sheet-name {:hdr true :fxn keyword})))

(comment
  (->map "excel-sample.xls" "test"))
```

[excel-sample.xls](https://github.com/kbosompem/bb-excel/files/13404568/excel-sample.xls)

**Comment by velios** [comment]
@avelino I'm sure somewhere in the documentation there is a note that the xls format is not supported. This is too complicated, because the format is proprietary and binary. I'm not sure it's worth checking the incoming file for its extension. Suddenly someone wants to use a file without an extension, but at the same time suitable for parsing by the library.

**Comment by avelino** [comment]
i didn't realize it didn't support xls, closing the issue

**Comment by velios** [comment]
@avelino I think you are right that this is not clearly described in the documentation. Also, the fact that xls, like xlsx, are essentially zip archives does differentiate it from each other with current checks. A similar problem will occur with any file type that is a zip archive, such as a jar. I will need to look for a unique element of the xlsx format that allows to clearly distinguish it from other formats.

**Comment by velios** [comment]
@avelino I found it. `Does not support older xls format` in **Limitations** section in README
